services:
  # vpn client
  # gluetun:
  #   container_name: gluetun
  #   image: qmcgaw/gluetun:latest
  #   restart: unless-stopped
  #   cap_add:
  #     - NET_ADMIN
  #   devices:
  #     - /dev/net/tun:/dev/net/tun
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/Zurich
  #     - VPN_SERVICE_PROVIDER=protonvpn
  #     - VPN_TYPE=wireguard
  #     - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
  #     - SERVER_COUNTRIES=Switzerland
  #     - UPDATER_PERIOD=24h
  #   volumes:
  #     - /home/media-center/config/gluetun:/gluetun
  #   ports:
  #     - 8080:8080 # qbittorrent webui

  swag:
    container_name: swag
    image: linuxserver/swag
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    volumes:
      - /home/media-center/config/swag:/config
    ports:
      - 80:80 # Make it accessible from the WAN by by configuring the NAT on your router to forward the port 80 to this host.
      - 443:443 # Make it accessible from the WAN by by configuring the NAT on your router to forward the port 443 to this host.
      - 81:81 # Keep the dashboard only accessible from you LAN.
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich,
      - URL=domain.ch
      - SUBDOMAINS=overseer,plex
      - EMAIL=my@domain.ch
      - ONLY_SUBDOMAINS=true
      - STAGING=true # IMPORTANT: Keep to True when you are testing otherwise you will reach the limit very quickly.
      - SWAG_AUTORELOAD=true
      - DOCKER_MODS=linuxserver/mods:swag-dashboard # proxy dashboard available at the address http://<host>:81

  qbittorrent:
    container_name: qbittorrent
    image: linuxserver/qbittorrent:latest
    restart: unless-stopped
    volumes:
      - /home/media-center/config/qbittorrent:/config
      - /home/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    # network_mode: service:gluetun
    # depends_on:
    #   - gluetun

  sabnzbd:
    container_name: sabnzbd
    image: linuxserver/sabnzbd:latest
    restart: unless-stopped
    volumes:
      - /home/media-center/config/sabnzbd:/config
      - /home/downloads:/downloads
    ports:
      - 6789:8080
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich

  plex:
    container_name: plex
    image: linuxserver/plex:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - /home/media-center/config/plex:/config
      - /media/hdd1/data/media:/data/media
    ports:
      - 32400:32400
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - VERSION=docker

  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:latest
    restart: unless-stopped
    volumes:
      - /home/media-center/config/prowlarr:/config
    ports:
      - 9696:9696
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    volumes:
      - /home/media-center/config/radarr:/config
      - /media/hdd1/data:/data
      - /home/downloads:/downloads
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    volumes:
      - /home/media-center/config/sonarr:/config
      - /media/hdd1/data:/data
      - /home/downloads:/downloads
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich

  overseerr:
    container_name: overseerr
    image: linuxserver/overseerr:latest
    restart: unless-stopped
    volumes:
      - /home/media-center/config/overseerr:/config
    ports:
      - 5055:5055
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr:latest
    restart: unless-stopped
    volumes:
      - /home/media-center/config/bazarr:/config
      - /media/hdd1/data:/data
    ports:
      - 6767:6767
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich

  flaresolverr:
    container_name: flaresolverr
    image: flaresolverr/flaresolverr:latest
    restart: unless-stopped
    ports:
      - 8191:8191
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Zurich

  # system monitoring dashboard
  glances:
    container_name: glances
    image: nicolargo/glances:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "GLANCES_OPT=-w"
    ports:
      - 61208-61209:61208-61209

  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:latest
    restart: unless-stopped
    ports:
      - 8081:80
    volumes:
      - /home/media-center/config/filebrowser:/config
      - /media/hdd1:/srv/hdd1
      - /home/media-center:/srv/media-center
      - /home/downloads:/srv/downloads
    environment:
      - PUID=1000
      - PGID=1000
